version: '3'

services:
  api:
    image: ${IMAGE_PATH:-api}:${IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - "80:3000"
